services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
